### ISSUE TITLE
Issue with requirments.txt install

### ISSUE THREAD

**Issue by mrconnerton** [zachseifts/aegir_deployment#1]
I have started with a blank ubuntu 10.04 server. I installed aegir and jenkins no problem.

Then it came time to install the requirements and I think it pooped on me. I'm not 100% how to interpret the errors:

``` shell
root@aegir:~# sudo apt-get install python-virtualenv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  python-pip python-setuptools
The following NEW packages will be installed:
  python-pip python-setuptools python-virtualenv
0 upgraded, 3 newly installed, 0 to remove and 2 not upgraded.
Need to get 320kB of archives.
After this operation, 2,245kB of additional disk space will be used.
Do you want to continue [Y/n]? Y
Get:1 http://us.archive.ubuntu.com/ubuntu/ lucid/main python-setuptools 0.6.10-4ubuntu1 [213kB]
Get:2 http://us.archive.ubuntu.com/ubuntu/ lucid-updates/universe python-pip 0.3.1-1ubuntu2.1 [49.8kB]
Get:3 http://us.archive.ubuntu.com/ubuntu/ lucid/universe python-virtualenv 1.4.5-1ubuntu1 [57.5kB]
Fetched 320kB in 0s (349kB/s)         
Selecting previously deselected package python-setuptools.
(Reading database ... 28871 files and directories currently installed.)
Unpacking python-setuptools (from .../python-setuptools_0.6.10-4ubuntu1_all.deb) ...
Selecting previously deselected package python-pip.
Unpacking python-pip (from .../python-pip_0.3.1-1ubuntu2.1_all.deb) ...
Selecting previously deselected package python-virtualenv.
Unpacking python-virtualenv (from .../python-virtualenv_1.4.5-1ubuntu1_all.deb) ...
Processing triggers for man-db ...
Setting up python-setuptools (0.6.10-4ubuntu1) ...

Processing triggers for python-central ...
Setting up python-pip (0.3.1-1ubuntu2.1) ...

Processing triggers for python-central ...
Setting up python-virtualenv (1.4.5-1ubuntu1) ...

Processing triggers for python-support ...
root@aegir:~# su jenkins
jenkins@aegir:/root$ cd
jenkins@aegir:~$ cd scripts/aegir_deployment/
jenkins@aegir:~/scripts/aegir_deployment$ virtualenv env
New python executable in env/bin/python
Installing distribute..................................................................................................................................................................................done.
jenkins@aegir:~/scripts/aegir_deployment$ ./env/bin/pip install -r requirements.txt
Downloading/unpacking Fabric==1.4.2 (from -r requirements.txt (line 1))
  Downloading Fabric-1.4.2.tar.gz (182Kb): 182Kb downloaded
  Running setup.py egg_info for package Fabric
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no files found matching 'fabfile.py'
Downloading/unpacking ssh>=1.7.14 (from Fabric==1.4.2->-r requirements.txt (line 1))
  Downloading ssh-1.7.14.tar.gz (794Kb): 794Kb downloaded
  Running setup.py egg_info for package ssh
Downloading/unpacking pycrypto>=2.1,!=2.4 (from ssh>=1.7.14->Fabric==1.4.2->-r requirements.txt (line 1))
  Downloading pycrypto-2.6.tar.gz (443Kb): 443Kb downloaded
  Running setup.py egg_info for package pycrypto
Installing collected packages: Fabric, ssh, pycrypto
  Running setup.py install for Fabric
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no files found matching 'fabfile.py'
    Installing fab script to /var/lib/jenkins/scripts/aegir_deployment/env/bin
  Running setup.py install for ssh
  Running setup.py install for pycrypto
    checking for gcc... no
    checking for cc... no
    checking for cl.exe... no
    configure: error: in `/var/lib/jenkins/scripts/aegir_deployment/env/build/pycrypto':
    configure: error: no acceptable C compiler found in $PATH
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/lib/jenkins/scripts/aegir_deployment/env/build/pycrypto/setup.py", line 456, in <module>
        core.setup(**kw)
      File "/usr/lib/python2.6/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib/python2.6/distutils/dist.py", line 975, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
        cmd_obj.run()
      File "/var/lib/jenkins/scripts/aegir_deployment/env/lib/python2.6/site-packages/distribute-0.6.10-py2.6.egg/setuptools/command/install.py", line 53, in run
        return _install.run(self)
      File "/usr/lib/python2.6/distutils/command/install.py", line 615, in run
        self.run_command('build')
      File "/usr/lib/python2.6/distutils/cmd.py", line 333, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.6/distutils/cmd.py", line 333, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
        cmd_obj.run()
      File "/var/lib/jenkins/scripts/aegir_deployment/env/build/pycrypto/setup.py", line 251, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.6/distutils/cmd.py", line 333, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
        cmd_obj.run()
      File "/var/lib/jenkins/scripts/aegir_deployment/env/build/pycrypto/setup.py", line 278, in run
        raise RuntimeError("autoconf error")
    RuntimeError: autoconf error
    Complete output from command /var/lib/jenkins/scripts/aegir_deployment/env/bin/python -c "import setuptools;__file__='/var/lib/jenkins/scripts/aegir_deployment/env/build/pycrypto/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-FspHOF-record/install-record.txt --install-headers /var/lib/jenkins/scripts/aegir_deployment/env/include/site/python2.6:
    running install

running build

running build_py

creating build

creating build/lib.linux-i686-2.6

creating build/lib.linux-i686-2.6/Crypto

copying lib/Crypto/pct_warnings.py -> build/lib.linux-i686-2.6/Crypto

copying lib/Crypto/__init__.py -> build/lib.linux-i686-2.6/Crypto

creating build/lib.linux-i686-2.6/Crypto/Hash

copying lib/Crypto/Hash/MD4.py -> build/lib.linux-i686-2.6/Crypto/Hash

copying lib/Crypto/Hash/hashalgo.py -> build/lib.linux-i686-2.6/Crypto/Hash

copying lib/Crypto/Hash/RIPEMD.py -> build/lib.linux-i686-2.6/Crypto/Hash

copying lib/Crypto/Hash/SHA224.py -> build/lib.linux-i686-2.6/Crypto/Hash

copying lib/Crypto/Hash/SHA512.py -> build/lib.linux-i686-2.6/Crypto/Hash

copying lib/Crypto/Hash/SHA384.py -> build/lib.linux-i686-2.6/Crypto/Hash

copying lib/Crypto/Hash/MD2.py -> build/lib.linux-i686-2.6/Crypto/Hash

copying lib/Crypto/Hash/HMAC.py -> build/lib.linux-i686-2.6/Crypto/Hash

copying lib/Crypto/Hash/SHA.py -> build/lib.linux-i686-2.6/Crypto/Hash

copying lib/Crypto/Hash/SHA256.py -> build/lib.linux-i686-2.6/Crypto/Hash

copying lib/Crypto/Hash/__init__.py -> build/lib.linux-i686-2.6/Crypto/Hash

copying lib/Crypto/Hash/MD5.py -> build/lib.linux-i686-2.6/Crypto/Hash

creating build/lib.linux-i686-2.6/Crypto/Cipher

copying lib/Crypto/Cipher/PKCS1_v1_5.py -> build/lib.linux-i686-2.6/Crypto/Cipher

copying lib/Crypto/Cipher/PKCS1_OAEP.py -> build/lib.linux-i686-2.6/Crypto/Cipher

copying lib/Crypto/Cipher/ARC4.py -> build/lib.linux-i686-2.6/Crypto/Cipher

copying lib/Crypto/Cipher/blockalgo.py -> build/lib.linux-i686-2.6/Crypto/Cipher

copying lib/Crypto/Cipher/DES.py -> build/lib.linux-i686-2.6/Crypto/Cipher

copying lib/Crypto/Cipher/DES3.py -> build/lib.linux-i686-2.6/Crypto/Cipher

copying lib/Crypto/Cipher/AES.py -> build/lib.linux-i686-2.6/Crypto/Cipher

copying lib/Crypto/Cipher/__init__.py -> build/lib.linux-i686-2.6/Crypto/Cipher

copying lib/Crypto/Cipher/XOR.py -> build/lib.linux-i686-2.6/Crypto/Cipher

copying lib/Crypto/Cipher/CAST.py -> build/lib.linux-i686-2.6/Crypto/Cipher

copying lib/Crypto/Cipher/ARC2.py -> build/lib.linux-i686-2.6/Crypto/Cipher

copying lib/Crypto/Cipher/Blowfish.py -> build/lib.linux-i686-2.6/Crypto/Cipher

creating build/lib.linux-i686-2.6/Crypto/Util

copying lib/Crypto/Util/Counter.py -> build/lib.linux-i686-2.6/Crypto/Util

copying lib/Crypto/Util/asn1.py -> build/lib.linux-i686-2.6/Crypto/Util

copying lib/Crypto/Util/_number_new.py -> build/lib.linux-i686-2.6/Crypto/Util

copying lib/Crypto/Util/randpool.py -> build/lib.linux-i686-2.6/Crypto/Util

copying lib/Crypto/Util/winrandom.py -> build/lib.linux-i686-2.6/Crypto/Util

copying lib/Crypto/Util/py21compat.py -> build/lib.linux-i686-2.6/Crypto/Util

copying lib/Crypto/Util/py3compat.py -> build/lib.linux-i686-2.6/Crypto/Util

copying lib/Crypto/Util/RFC1751.py -> build/lib.linux-i686-2.6/Crypto/Util

copying lib/Crypto/Util/__init__.py -> build/lib.linux-i686-2.6/Crypto/Util

copying lib/Crypto/Util/number.py -> build/lib.linux-i686-2.6/Crypto/Util

creating build/lib.linux-i686-2.6/Crypto/Random

copying lib/Crypto/Random/random.py -> build/lib.linux-i686-2.6/Crypto/Random

copying lib/Crypto/Random/_UserFriendlyRNG.py -> build/lib.linux-i686-2.6/Crypto/Random

copying lib/Crypto/Random/__init__.py -> build/lib.linux-i686-2.6/Crypto/Random

creating build/lib.linux-i686-2.6/Crypto/Random/Fortuna

copying lib/Crypto/Random/Fortuna/SHAd256.py -> build/lib.linux-i686-2.6/Crypto/Random/Fortuna

copying lib/Crypto/Random/Fortuna/FortunaAccumulator.py -> build/lib.linux-i686-2.6/Crypto/Random/Fortuna

copying lib/Crypto/Random/Fortuna/__init__.py -> build/lib.linux-i686-2.6/Crypto/Random/Fortuna

copying lib/Crypto/Random/Fortuna/FortunaGenerator.py -> build/lib.linux-i686-2.6/Crypto/Random/Fortuna

creating build/lib.linux-i686-2.6/Crypto/Random/OSRNG

copying lib/Crypto/Random/OSRNG/fallback.py -> build/lib.linux-i686-2.6/Crypto/Random/OSRNG

copying lib/Crypto/Random/OSRNG/posix.py -> build/lib.linux-i686-2.6/Crypto/Random/OSRNG

copying lib/Crypto/Random/OSRNG/nt.py -> build/lib.linux-i686-2.6/Crypto/Random/OSRNG

copying lib/Crypto/Random/OSRNG/rng_base.py -> build/lib.linux-i686-2.6/Crypto/Random/OSRNG

copying lib/Crypto/Random/OSRNG/__init__.py -> build/lib.linux-i686-2.6/Crypto/Random/OSRNG

creating build/lib.linux-i686-2.6/Crypto/SelfTest

copying lib/Crypto/SelfTest/__init__.py -> build/lib.linux-i686-2.6/Crypto/SelfTest

copying lib/Crypto/SelfTest/st_common.py -> build/lib.linux-i686-2.6/Crypto/SelfTest

creating build/lib.linux-i686-2.6/Crypto/SelfTest/Cipher

copying lib/Crypto/SelfTest/Cipher/test_pkcs1_oaep.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Cipher

copying lib/Crypto/SelfTest/Cipher/test_XOR.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Cipher

copying lib/Crypto/SelfTest/Cipher/test_DES.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Cipher

copying lib/Crypto/SelfTest/Cipher/test_pkcs1_15.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Cipher

copying lib/Crypto/SelfTest/Cipher/test_CAST.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Cipher

copying lib/Crypto/SelfTest/Cipher/test_Blowfish.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Cipher

copying lib/Crypto/SelfTest/Cipher/test_ARC2.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Cipher

copying lib/Crypto/SelfTest/Cipher/test_ARC4.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Cipher

copying lib/Crypto/SelfTest/Cipher/test_AES.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Cipher

copying lib/Crypto/SelfTest/Cipher/test_DES3.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Cipher

copying lib/Crypto/SelfTest/Cipher/__init__.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Cipher

copying lib/Crypto/SelfTest/Cipher/common.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Cipher

creating build/lib.linux-i686-2.6/Crypto/SelfTest/Hash

copying lib/Crypto/SelfTest/Hash/test_SHA256.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Hash

copying lib/Crypto/SelfTest/Hash/test_RIPEMD.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Hash

copying lib/Crypto/SelfTest/Hash/test_SHA224.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Hash

copying lib/Crypto/SelfTest/Hash/test_MD2.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Hash

copying lib/Crypto/SelfTest/Hash/test_MD5.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Hash

copying lib/Crypto/SelfTest/Hash/test_HMAC.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Hash

copying lib/Crypto/SelfTest/Hash/test_SHA.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Hash

copying lib/Crypto/SelfTest/Hash/test_SHA384.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Hash

copying lib/Crypto/SelfTest/Hash/test_SHA512.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Hash

copying lib/Crypto/SelfTest/Hash/__init__.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Hash

copying lib/Crypto/SelfTest/Hash/common.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Hash

copying lib/Crypto/SelfTest/Hash/test_MD4.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Hash

creating build/lib.linux-i686-2.6/Crypto/SelfTest/Protocol

copying lib/Crypto/SelfTest/Protocol/test_KDF.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Protocol

copying lib/Crypto/SelfTest/Protocol/test_rfc1751.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Protocol

copying lib/Crypto/SelfTest/Protocol/test_chaffing.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Protocol

copying lib/Crypto/SelfTest/Protocol/__init__.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Protocol

copying lib/Crypto/SelfTest/Protocol/test_AllOrNothing.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Protocol

creating build/lib.linux-i686-2.6/Crypto/SelfTest/PublicKey

copying lib/Crypto/SelfTest/PublicKey/test_importKey.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/PublicKey

copying lib/Crypto/SelfTest/PublicKey/test_ElGamal.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/PublicKey

copying lib/Crypto/SelfTest/PublicKey/test_DSA.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/PublicKey

copying lib/Crypto/SelfTest/PublicKey/test_RSA.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/PublicKey

copying lib/Crypto/SelfTest/PublicKey/__init__.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/PublicKey

creating build/lib.linux-i686-2.6/Crypto/SelfTest/Random

copying lib/Crypto/SelfTest/Random/test_random.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Random

copying lib/Crypto/SelfTest/Random/__init__.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Random

copying lib/Crypto/SelfTest/Random/test_rpoolcompat.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Random

creating build/lib.linux-i686-2.6/Crypto/SelfTest/Random/Fortuna

copying lib/Crypto/SelfTest/Random/Fortuna/test_SHAd256.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Random/Fortuna

copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaGenerator.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Random/Fortuna

copying lib/Crypto/SelfTest/Random/Fortuna/__init__.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Random/Fortuna

copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaAccumulator.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Random/Fortuna

creating build/lib.linux-i686-2.6/Crypto/SelfTest/Random/OSRNG

copying lib/Crypto/SelfTest/Random/OSRNG/test_winrandom.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Random/OSRNG

copying lib/Crypto/SelfTest/Random/OSRNG/test_nt.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Random/OSRNG

copying lib/Crypto/SelfTest/Random/OSRNG/test_fallback.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Random/OSRNG

copying lib/Crypto/SelfTest/Random/OSRNG/test_posix.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Random/OSRNG

copying lib/Crypto/SelfTest/Random/OSRNG/test_generic.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Random/OSRNG

copying lib/Crypto/SelfTest/Random/OSRNG/__init__.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Random/OSRNG

creating build/lib.linux-i686-2.6/Crypto/SelfTest/Util

copying lib/Crypto/SelfTest/Util/test_number.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Util

copying lib/Crypto/SelfTest/Util/test_asn1.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Util

copying lib/Crypto/SelfTest/Util/test_winrandom.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Util

copying lib/Crypto/SelfTest/Util/test_Counter.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Util

copying lib/Crypto/SelfTest/Util/__init__.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Util

creating build/lib.linux-i686-2.6/Crypto/SelfTest/Signature

copying lib/Crypto/SelfTest/Signature/test_pkcs1_15.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Signature

copying lib/Crypto/SelfTest/Signature/test_pkcs1_pss.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Signature

copying lib/Crypto/SelfTest/Signature/__init__.py -> build/lib.linux-i686-2.6/Crypto/SelfTest/Signature

creating build/lib.linux-i686-2.6/Crypto/Protocol

copying lib/Crypto/Protocol/AllOrNothing.py -> build/lib.linux-i686-2.6/Crypto/Protocol

copying lib/Crypto/Protocol/Chaffing.py -> build/lib.linux-i686-2.6/Crypto/Protocol

copying lib/Crypto/Protocol/__init__.py -> build/lib.linux-i686-2.6/Crypto/Protocol

copying lib/Crypto/Protocol/KDF.py -> build/lib.linux-i686-2.6/Crypto/Protocol

creating build/lib.linux-i686-2.6/Crypto/PublicKey

copying lib/Crypto/PublicKey/_DSA.py -> build/lib.linux-i686-2.6/Crypto/PublicKey

copying lib/Crypto/PublicKey/_RSA.py -> build/lib.linux-i686-2.6/Crypto/PublicKey

copying lib/Crypto/PublicKey/RSA.py -> build/lib.linux-i686-2.6/Crypto/PublicKey

copying lib/Crypto/PublicKey/_slowmath.py -> build/lib.linux-i686-2.6/Crypto/PublicKey

copying lib/Crypto/PublicKey/ElGamal.py -> build/lib.linux-i686-2.6/Crypto/PublicKey

copying lib/Crypto/PublicKey/pubkey.py -> build/lib.linux-i686-2.6/Crypto/PublicKey

copying lib/Crypto/PublicKey/DSA.py -> build/lib.linux-i686-2.6/Crypto/PublicKey

copying lib/Crypto/PublicKey/__init__.py -> build/lib.linux-i686-2.6/Crypto/PublicKey

creating build/lib.linux-i686-2.6/Crypto/Signature

copying lib/Crypto/Signature/PKCS1_PSS.py -> build/lib.linux-i686-2.6/Crypto/Signature

copying lib/Crypto/Signature/PKCS1_v1_5.py -> build/lib.linux-i686-2.6/Crypto/Signature

copying lib/Crypto/Signature/__init__.py -> build/lib.linux-i686-2.6/Crypto/Signature

running build_ext

running build_configure

checking for gcc... no

checking for cc... no

checking for cl.exe... no

configure: error: in `/var/lib/jenkins/scripts/aegir_deployment/env/build/pycrypto':

configure: error: no acceptable C compiler found in $PATH

See `config.log' for more details

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/var/lib/jenkins/scripts/aegir_deployment/env/build/pycrypto/setup.py", line 456, in <module>

    core.setup(**kw)

  File "/usr/lib/python2.6/distutils/core.py", line 152, in setup

    dist.run_commands()

  File "/usr/lib/python2.6/distutils/dist.py", line 975, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command

    cmd_obj.run()

  File "/var/lib/jenkins/scripts/aegir_deployment/env/lib/python2.6/site-packages/distribute-0.6.10-py2.6.egg/setuptools/command/install.py", line 53, in run

    return _install.run(self)

  File "/usr/lib/python2.6/distutils/command/install.py", line 615, in run

    self.run_command('build')

  File "/usr/lib/python2.6/distutils/cmd.py", line 333, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.6/distutils/command/build.py", line 135, in run

    self.run_command(cmd_name)

  File "/usr/lib/python2.6/distutils/cmd.py", line 333, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command

    cmd_obj.run()

  File "/var/lib/jenkins/scripts/aegir_deployment/env/build/pycrypto/setup.py", line 251, in run

    self.run_command(cmd_name)

  File "/usr/lib/python2.6/distutils/cmd.py", line 333, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command

    cmd_obj.run()

  File "/var/lib/jenkins/scripts/aegir_deployment/env/build/pycrypto/setup.py", line 278, in run

    raise RuntimeError("autoconf error")

RuntimeError: autoconf error

----------------------------------------
Command /var/lib/jenkins/scripts/aegir_deployment/env/bin/python -c "import setuptools;__file__='/var/lib/jenkins/scripts/aegir_deployment/env/build/pycrypto/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-FspHOF-record/install-record.txt --install-headers /var/lib/jenkins/scripts/aegir_deployment/env/include/site/python2.6 failed with error code 1 in /var/lib/jenkins/scripts/aegir_deployment/env/build/pycrypto
Storing complete log in /var/lib/jenkins/.pip/pip.log
jenkins@aegir:~/scripts/aegir_deployment$ fab
The program 'fab' is currently not installed.  To run 'fab' please ask your administrator to install the package 'fabric'
jenkins@aegir:~/scripts/aegir_deployment$ 

```

**Comment by zachseifts** [comment]
Do you have `build-essential` installed? It looks like pycrypto needs the gcc or cc compiles and it's crapping out when it doesn't find them on the system. I would check `aptitude show build-essential` and see what it says for the status.

**Comment by zachseifts** [comment]
What version of virtualenv are you running? The 2nd command should show you that. In older versions of virtualenv you have to specify `--no-site-packages` to make it ignore the default sites-packages for your python install. It may be related to that

**Comment by zachseifts** [comment]
I think it's related to not having `build-essential` installed. Check this out: http://ubuntuforums.org/showthread.php?t=1696998

**Comment by mrconnerton** [comment]
I have 1.4.5 of virtualenv

I did not have build-essential. I installed that and reran the install and it failed again during the compiling with 

``` shell
configure: creating ./config.status
    config.status: creating src/config.h
    warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
    building 'Crypto.Hash._MD2' extension
    gcc -pthread -fno-strict-aliasing -fwrapv -Wall -Wstrict-prototypes -fPIC -std=c99 -O3 -fomit-frame-pointer -Isrc/ -I/usr/include/python2.6 -c src/MD2.c -o build/temp.linux-i686-2.6/src/MD2.o
```

I went right into installing aegir and letting it manage the lamp part instead of installing it all normally like I do so I'm sure I'm missing some packages. I will google the errors as I get em.

**Comment by mrconnerton** [comment]
apt-get install python-dev got me the rest of the way

**Comment by zachseifts** [comment]
Hum, which version of python are you using? You might need to grab the python dev headers. I think it's `aptitude install python-dev`

**Comment by mrconnerton** [comment]
:-)

**Comment by zachseifts** [comment]
Awesome, I added a note in the readme about 10.04 installs. Thanks!
